/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as CartRouteImport } from './routes/cart'
import { Route as DividendRouteImport } from './routes/dividend'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as MemberCenterRouteImport } from './routes/member-center'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TrialRouteImport } from './routes/trial'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminForecastingRouteImport } from './routes/admin.forecasting'
import { Route as AdminLogisticsRouteImport } from './routes/admin.logistics'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminPreordersRouteImport } from './routes/admin.preorders'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSurplusRouteImport } from './routes/admin.surplus'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminVotingRouteImport } from './routes/admin.voting'
import { Route as AdminWishlistRouteImport } from './routes/admin.wishlist'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const DividendRoute = DividendRouteImport.update({
  id: '/dividend',
  path: '/dividend',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberCenterRoute = MemberCenterRouteImport.update({
  id: '/member-center',
  path: '/member-center',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TrialRoute = TrialRouteImport.update({
  id: '/trial',
  path: '/trial',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminForecastingRoute = AdminForecastingRouteImport.update({
  id: '/forecasting',
  path: '/forecasting',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogisticsRoute = AdminLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPreordersRoute = AdminPreordersRouteImport.update({
  id: '/preorders',
  path: '/preorders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSurplusRoute = AdminSurplusRouteImport.update({
  id: '/surplus',
  path: '/surplus',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVotingRoute = AdminVotingRouteImport.update({
  id: '/voting',
  path: '/voting',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWishlistRoute = AdminWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/cart': typeof CartRoute
  '/dividend': typeof DividendRoute
  '/governance': typeof GovernanceRoute
  '/impact': typeof ImpactRoute
  '/member-center': typeof MemberCenterRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/trial': typeof TrialRoute
  '/verify': typeof VerifyRoute
  '/wishlist': typeof WishlistRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/forecasting': typeof AdminForecastingRoute
  '/admin/logistics': typeof AdminLogisticsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/preorders': typeof AdminPreordersRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/surplus': typeof AdminSurplusRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/voting': typeof AdminVotingRoute
  '/admin/wishlist': typeof AdminWishlistRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/cart': typeof CartRoute
  '/dividend': typeof DividendRoute
  '/governance': typeof GovernanceRoute
  '/impact': typeof ImpactRoute
  '/member-center': typeof MemberCenterRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/trial': typeof TrialRoute
  '/verify': typeof VerifyRoute
  '/wishlist': typeof WishlistRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/forecasting': typeof AdminForecastingRoute
  '/admin/logistics': typeof AdminLogisticsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/preorders': typeof AdminPreordersRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/surplus': typeof AdminSurplusRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/voting': typeof AdminVotingRoute
  '/admin/wishlist': typeof AdminWishlistRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/cart': typeof CartRoute
  '/dividend': typeof DividendRoute
  '/governance': typeof GovernanceRoute
  '/impact': typeof ImpactRoute
  '/member-center': typeof MemberCenterRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/trial': typeof TrialRoute
  '/verify': typeof VerifyRoute
  '/wishlist': typeof WishlistRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/forecasting': typeof AdminForecastingRoute
  '/admin/logistics': typeof AdminLogisticsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/preorders': typeof AdminPreordersRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/surplus': typeof AdminSurplusRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/voting': typeof AdminVotingRoute
  '/admin/wishlist': typeof AdminWishlistRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calculator'
    | '/cart'
    | '/dividend'
    | '/governance'
    | '/impact'
    | '/member-center'
    | '/onboarding'
    | '/orders'
    | '/register'
    | '/trial'
    | '/verify'
    | '/wishlist'
    | '/admin/finance'
    | '/admin/forecasting'
    | '/admin/logistics'
    | '/admin/members'
    | '/admin/preorders'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/surplus'
    | '/admin/users'
    | '/admin/voting'
    | '/admin/wishlist'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/cart'
    | '/dividend'
    | '/governance'
    | '/impact'
    | '/member-center'
    | '/onboarding'
    | '/orders'
    | '/register'
    | '/trial'
    | '/verify'
    | '/wishlist'
    | '/admin/finance'
    | '/admin/forecasting'
    | '/admin/logistics'
    | '/admin/members'
    | '/admin/preorders'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/surplus'
    | '/admin/users'
    | '/admin/voting'
    | '/admin/wishlist'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/calculator'
    | '/cart'
    | '/dividend'
    | '/governance'
    | '/impact'
    | '/member-center'
    | '/onboarding'
    | '/orders'
    | '/register'
    | '/trial'
    | '/verify'
    | '/wishlist'
    | '/admin/finance'
    | '/admin/forecasting'
    | '/admin/logistics'
    | '/admin/members'
    | '/admin/preorders'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/surplus'
    | '/admin/users'
    | '/admin/voting'
    | '/admin/wishlist'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CalculatorRoute: typeof CalculatorRoute
  CartRoute: typeof CartRoute
  DividendRoute: typeof DividendRoute
  GovernanceRoute: typeof GovernanceRoute
  ImpactRoute: typeof ImpactRoute
  MemberCenterRoute: typeof MemberCenterRoute
  OnboardingRoute: typeof OnboardingRoute
  OrdersRoute: typeof OrdersRoute
  RegisterRoute: typeof RegisterRoute
  TrialRoute: typeof TrialRoute
  VerifyRoute: typeof VerifyRoute
  WishlistRoute: typeof WishlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dividend': {
      id: '/dividend'
      path: '/dividend'
      fullPath: '/dividend'
      preLoaderRoute: typeof DividendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member-center': {
      id: '/member-center'
      path: '/member-center'
      fullPath: '/member-center'
      preLoaderRoute: typeof MemberCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trial': {
      id: '/trial'
      path: '/trial'
      fullPath: '/trial'
      preLoaderRoute: typeof TrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forecasting': {
      id: '/admin/forecasting'
      path: '/forecasting'
      fullPath: '/admin/forecasting'
      preLoaderRoute: typeof AdminForecastingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logistics': {
      id: '/admin/logistics'
      path: '/logistics'
      fullPath: '/admin/logistics'
      preLoaderRoute: typeof AdminLogisticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/preorders': {
      id: '/admin/preorders'
      path: '/preorders'
      fullPath: '/admin/preorders'
      preLoaderRoute: typeof AdminPreordersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/surplus': {
      id: '/admin/surplus'
      path: '/surplus'
      fullPath: '/admin/surplus'
      preLoaderRoute: typeof AdminSurplusRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/voting': {
      id: '/admin/voting'
      path: '/voting'
      fullPath: '/admin/voting'
      preLoaderRoute: typeof AdminVotingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wishlist': {
      id: '/admin/wishlist'
      path: '/wishlist'
      fullPath: '/admin/wishlist'
      preLoaderRoute: typeof AdminWishlistRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminForecastingRoute: typeof AdminForecastingRoute
  AdminLogisticsRoute: typeof AdminLogisticsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminPreordersRoute: typeof AdminPreordersRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminSurplusRoute: typeof AdminSurplusRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVotingRoute: typeof AdminVotingRoute
  AdminWishlistRoute: typeof AdminWishlistRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFinanceRoute: AdminFinanceRoute,
  AdminForecastingRoute: AdminForecastingRoute,
  AdminLogisticsRoute: AdminLogisticsRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminPreordersRoute: AdminPreordersRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminSurplusRoute: AdminSurplusRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVotingRoute: AdminVotingRoute,
  AdminWishlistRoute: AdminWishlistRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CalculatorRoute: CalculatorRoute,
  CartRoute: CartRoute,
  DividendRoute: DividendRoute,
  GovernanceRoute: GovernanceRoute,
  ImpactRoute: ImpactRoute,
  MemberCenterRoute: MemberCenterRoute,
  OnboardingRoute: OnboardingRoute,
  OrdersRoute: OrdersRoute,
  RegisterRoute: RegisterRoute,
  TrialRoute: TrialRoute,
  VerifyRoute: VerifyRoute,
  WishlistRoute: WishlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
